let forecast = {
  location: {
    name: "Berlin",
    region: "Berlin",
    country: "Germany",
    lat: 52.52,
    lon: 13.4,
    tz_id: "Europe/Berlin",
    localtime_epoch: 1651315258,
    localtime: "2022-04-30 12:40",
  },
  current: {
    last_updated_epoch: 1651314600,
    last_updated: "2022-04-30 12:30",
    temp_c: 17.0,
    is_day: 1,
    condition: {
      text: "Sunny",
      icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
      code: 1000,
    },
    wind_kph: 3.6,
    wind_degree: 300,
    cloud: 0,
    feelslike_c: 17.0,
    uv: 4.0,
  },
  forecast: {
    forecastday: [
      {
        date: "2022-04-30",
        date_epoch: 1651276800,
        day: {
          maxtemp_c: 19.5,
          maxtemp_f: 67.1,
          mintemp_c: 10.0,
          mintemp_f: 50.0,
          avgtemp_c: 14.2,
          avgtemp_f: 57.6,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Overcast",
            icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
            code: 1009,
          },
        },
        astro: {
          sunrise: "05:38 AM",
          sunset: "08:31 PM",
          moonrise: "05:41 AM",
          moonset: "08:12 PM",
          moon_phase: "New Moon",
          moon_illumination: "0",
        },
        hour: [
          {
            time_epoch: 1651269600,
            time: "2022-04-30 00:00",
            temp_c: 12.5,
            temp_f: 54.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 48,
            feelslike_c: 11.9,
            feelslike_f: 53.4,
            heatindex_c: 12.5,
            heatindex_f: 54.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651273200,
            time: "2022-04-30 01:00",
            temp_c: 11.5,
            temp_f: 52.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 38,
            feelslike_c: 10.6,
            feelslike_f: 51.1,
            heatindex_c: 11.5,
            heatindex_f: 52.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651276800,
            time: "2022-04-30 02:00",
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 60,
            feelslike_c: 10.2,
            feelslike_f: 50.4,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651280400,
            time: "2022-04-30 03:00",
            temp_c: 10.6,
            temp_f: 51.1,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            cloud: 83,
            feelslike_c: 10.2,
            feelslike_f: 50.4,
            heatindex_c: 10.6,
            heatindex_f: 51.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651284000,
            time: "2022-04-30 04:00",
            temp_c: 10.3,
            temp_f: 50.5,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 10.3,
            feelslike_f: 50.5,
            heatindex_c: 10.3,
            heatindex_f: 50.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651287600,
            time: "2022-04-30 05:00",
            temp_c: 10.0,
            temp_f: 50.0,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 97,
            feelslike_c: 10.2,
            feelslike_f: 50.4,
            heatindex_c: 10.0,
            heatindex_f: 50.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651291200,
            time: "2022-04-30 06:00",
            temp_c: 10.6,
            temp_f: 51.1,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 10.6,
            feelslike_f: 51.1,
            heatindex_c: 10.6,
            heatindex_f: 51.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651294800,
            time: "2022-04-30 07:00",
            temp_c: 11.8,
            temp_f: 53.2,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 61,
            feelslike_c: 11.8,
            feelslike_f: 53.2,
            heatindex_c: 11.8,
            heatindex_f: 53.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651298400,
            time: "2022-04-30 08:00",
            temp_c: 13.3,
            temp_f: 55.9,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 13.3,
            feelslike_f: 55.9,
            heatindex_c: 13.3,
            heatindex_f: 55.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651302000,
            time: "2022-04-30 09:00",
            temp_c: 14.8,
            temp_f: 58.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 15.7,
            feelslike_f: 60.3,
            heatindex_c: 14.8,
            heatindex_f: 58.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651305600,
            time: "2022-04-30 10:00",
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 99,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651309200,
            time: "2022-04-30 11:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651312800,
            time: "2022-04-30 12:00",
            temp_c: 18.3,
            temp_f: 64.9,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 18.3,
            feelslike_f: 64.9,
            heatindex_c: 18.3,
            heatindex_f: 64.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651316400,
            time: "2022-04-30 13:00",
            temp_c: 19.0,
            temp_f: 66.2,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 82,
            feelslike_c: 19.0,
            feelslike_f: 66.2,
            heatindex_c: 19.0,
            heatindex_f: 66.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651320000,
            time: "2022-04-30 14:00",
            temp_c: 19.3,
            temp_f: 66.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 48,
            feelslike_c: 19.3,
            feelslike_f: 66.7,
            heatindex_c: 19.3,
            heatindex_f: 66.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651323600,
            time: "2022-04-30 15:00",
            temp_c: 19.5,
            temp_f: 67.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 32,
            feelslike_c: 19.5,
            feelslike_f: 67.1,
            heatindex_c: 19.5,
            heatindex_f: 67.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651327200,
            time: "2022-04-30 16:00",
            temp_c: 18.9,
            temp_f: 66.0,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 28,
            feelslike_c: 18.9,
            feelslike_f: 66.0,
            heatindex_c: 18.9,
            heatindex_f: 66.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651330800,
            time: "2022-04-30 17:00",
            temp_c: 17.7,
            temp_f: 63.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 46,
            feelslike_c: 17.7,
            feelslike_f: 63.9,
            heatindex_c: 17.7,
            heatindex_f: 63.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651334400,
            time: "2022-04-30 18:00",
            temp_c: 16.7,
            temp_f: 62.1,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 52,
            feelslike_c: 16.7,
            feelslike_f: 62.1,
            heatindex_c: 16.7,
            heatindex_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651338000,
            time: "2022-04-30 19:00",
            temp_c: 15.5,
            temp_f: 59.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 29,
            feelslike_c: 15.5,
            feelslike_f: 59.9,
            heatindex_c: 15.5,
            heatindex_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651341600,
            time: "2022-04-30 20:00",
            temp_c: 13.5,
            temp_f: 56.3,
            is_day: 1,
            condition: {
              text: "Sunny",
              icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
              code: 1000,
            },
            cloud: 17,
            feelslike_c: 12.4,
            feelslike_f: 54.3,
            heatindex_c: 13.5,
            heatindex_f: 56.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651345200,
            time: "2022-04-30 21:00",
            temp_c: 12.1,
            temp_f: 53.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 25,
            feelslike_c: 10.7,
            feelslike_f: 51.3,
            heatindex_c: 12.1,
            heatindex_f: 53.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651348800,
            time: "2022-04-30 22:00",
            temp_c: 11.2,
            temp_f: 52.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 49,
            feelslike_c: 9.5,
            feelslike_f: 49.1,
            heatindex_c: 11.2,
            heatindex_f: 52.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651352400,
            time: "2022-04-30 23:00",
            temp_c: 10.4,
            temp_f: 50.7,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 45,
            feelslike_c: 8.5,
            feelslike_f: 47.3,
            heatindex_c: 10.4,
            heatindex_f: 50.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
        ],
      },
      {
        date: "2022-05-01",
        date_epoch: 1651363200,
        day: {
          maxtemp_c: 17.4,
          maxtemp_f: 63.3,
          mintemp_c: 9.4,
          mintemp_f: 48.9,
          avgtemp_c: 12.7,
          avgtemp_f: 54.9,
          daily_will_it_rain: 0,
          daily_chance_of_rain: 0,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
            code: 1006,
          },
        },
        astro: {
          sunrise: "05:36 AM",
          sunset: "08:32 PM",
          moonrise: "05:55 AM",
          moonset: "09:28 PM",
          moon_phase: "New Moon",
          moon_illumination: "0",
        },
        hour: [
          {
            time_epoch: 1651356000,
            time: "2022-05-01 00:00",
            temp_c: 9.9,
            temp_f: 49.8,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 47,
            feelslike_c: 8.2,
            feelslike_f: 46.8,
            heatindex_c: 9.9,
            heatindex_f: 49.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651359600,
            time: "2022-05-01 01:00",
            temp_c: 9.7,
            temp_f: 49.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 44,
            feelslike_c: 8.1,
            feelslike_f: 46.6,
            heatindex_c: 9.7,
            heatindex_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651363200,
            time: "2022-05-01 02:00",
            temp_c: 9.6,
            temp_f: 49.3,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 44,
            feelslike_c: 8.0,
            feelslike_f: 46.4,
            heatindex_c: 9.6,
            heatindex_f: 49.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651366800,
            time: "2022-05-01 03:00",
            temp_c: 9.7,
            temp_f: 49.5,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 47,
            feelslike_c: 8.0,
            feelslike_f: 46.4,
            heatindex_c: 9.7,
            heatindex_f: 49.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651370400,
            time: "2022-05-01 04:00",
            temp_c: 9.4,
            temp_f: 48.9,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 38,
            feelslike_c: 7.6,
            feelslike_f: 45.7,
            heatindex_c: 9.4,
            heatindex_f: 48.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651374000,
            time: "2022-05-01 05:00",
            temp_c: 9.5,
            temp_f: 49.1,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 47,
            feelslike_c: 7.9,
            feelslike_f: 46.2,
            heatindex_c: 9.5,
            heatindex_f: 49.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651377600,
            time: "2022-05-01 06:00",
            temp_c: 9.8,
            temp_f: 49.6,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 46,
            feelslike_c: 8.5,
            feelslike_f: 47.3,
            heatindex_c: 9.8,
            heatindex_f: 49.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651381200,
            time: "2022-05-01 07:00",
            temp_c: 10.4,
            temp_f: 50.7,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 9.4,
            feelslike_f: 48.9,
            heatindex_c: 10.4,
            heatindex_f: 50.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651384800,
            time: "2022-05-01 08:00",
            temp_c: 11.2,
            temp_f: 52.2,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 80,
            feelslike_c: 10.1,
            feelslike_f: 50.2,
            heatindex_c: 11.2,
            heatindex_f: 52.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651388400,
            time: "2022-05-01 09:00",
            temp_c: 12.7,
            temp_f: 54.9,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 71,
            feelslike_c: 11.7,
            feelslike_f: 53.1,
            heatindex_c: 12.7,
            heatindex_f: 54.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651392000,
            time: "2022-05-01 10:00",
            temp_c: 14.4,
            temp_f: 57.9,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 56,
            feelslike_c: 13.7,
            feelslike_f: 56.7,
            heatindex_c: 14.4,
            heatindex_f: 57.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651395600,
            time: "2022-05-01 11:00",
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 51,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651399200,
            time: "2022-05-01 12:00",
            temp_c: 17.0,
            temp_f: 62.6,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 71,
            feelslike_c: 17.0,
            feelslike_f: 62.6,
            heatindex_c: 17.0,
            heatindex_f: 62.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651402800,
            time: "2022-05-01 13:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 63,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651406400,
            time: "2022-05-01 14:00",
            temp_c: 16.8,
            temp_f: 62.2,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 67,
            feelslike_c: 16.8,
            feelslike_f: 62.2,
            heatindex_c: 16.8,
            heatindex_f: 62.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651410000,
            time: "2022-05-01 15:00",
            temp_c: 16.3,
            temp_f: 61.3,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 84,
            feelslike_c: 16.3,
            feelslike_f: 61.3,
            heatindex_c: 16.3,
            heatindex_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651413600,
            time: "2022-05-01 16:00",
            temp_c: 15.9,
            temp_f: 60.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 15.9,
            feelslike_f: 60.6,
            heatindex_c: 15.9,
            heatindex_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651417200,
            time: "2022-05-01 17:00",
            temp_c: 15.1,
            temp_f: 59.2,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 15.1,
            feelslike_f: 59.2,
            heatindex_c: 15.1,
            heatindex_f: 59.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651420800,
            time: "2022-05-01 18:00",
            temp_c: 14.2,
            temp_f: 57.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 13.3,
            feelslike_f: 55.9,
            heatindex_c: 14.2,
            heatindex_f: 57.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651424400,
            time: "2022-05-01 19:00",
            temp_c: 13.3,
            temp_f: 55.9,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 66,
            feelslike_c: 12.1,
            feelslike_f: 53.8,
            heatindex_c: 13.3,
            heatindex_f: 55.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651428000,
            time: "2022-05-01 20:00",
            temp_c: 12.2,
            temp_f: 54.0,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 84,
            feelslike_c: 10.8,
            feelslike_f: 51.4,
            heatindex_c: 12.2,
            heatindex_f: 54.0,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651431600,
            time: "2022-05-01 21:00",
            temp_c: 11.7,
            temp_f: 53.1,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 88,
            feelslike_c: 10.4,
            feelslike_f: 50.7,
            heatindex_c: 11.7,
            heatindex_f: 53.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651435200,
            time: "2022-05-01 22:00",
            temp_c: 11.5,
            temp_f: 52.7,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            cloud: 83,
            feelslike_c: 10.4,
            feelslike_f: 50.7,
            heatindex_c: 11.5,
            heatindex_f: 52.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651438800,
            time: "2022-05-01 23:00",
            temp_c: 11.3,
            temp_f: 52.3,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 93,
            feelslike_c: 10.3,
            feelslike_f: 50.5,
            heatindex_c: 11.3,
            heatindex_f: 52.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
        ],
      },
      {
        date: "2022-05-02",
        date_epoch: 1651449600,
        day: {
          maxtemp_c: 18.0,
          maxtemp_f: 64.4,
          mintemp_c: 10.1,
          mintemp_f: 50.2,
          avgtemp_c: 13.4,
          avgtemp_f: 56.1,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 78,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Patchy rain possible",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
        },
        astro: {
          sunrise: "05:34 AM",
          sunset: "08:34 PM",
          moonrise: "06:12 AM",
          moonset: "10:42 PM",
          moon_phase: "Waxing Crescent",
          moon_illumination: "5",
        },
        hour: [
          {
            time_epoch: 1651442400,
            time: "2022-05-02 00:00",
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 10.0,
            feelslike_f: 50.0,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651446000,
            time: "2022-05-02 01:00",
            temp_c: 10.8,
            temp_f: 51.4,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            cloud: 74,
            feelslike_c: 10.0,
            feelslike_f: 50.0,
            heatindex_c: 10.8,
            heatindex_f: 51.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651449600,
            time: "2022-05-02 02:00",
            temp_c: 10.6,
            temp_f: 51.1,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 10.0,
            feelslike_f: 50.0,
            heatindex_c: 10.6,
            heatindex_f: 51.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651453200,
            time: "2022-05-02 03:00",
            temp_c: 10.3,
            temp_f: 50.5,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 9.7,
            feelslike_f: 49.5,
            heatindex_c: 10.3,
            heatindex_f: 50.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651456800,
            time: "2022-05-02 04:00",
            temp_c: 10.1,
            temp_f: 50.2,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 9.8,
            feelslike_f: 49.6,
            heatindex_c: 10.1,
            heatindex_f: 50.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651460400,
            time: "2022-05-02 05:00",
            temp_c: 10.1,
            temp_f: 50.2,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 10.1,
            feelslike_f: 50.2,
            heatindex_c: 10.1,
            heatindex_f: 50.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651464000,
            time: "2022-05-02 06:00",
            temp_c: 10.3,
            temp_f: 50.5,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 99,
            feelslike_c: 10.4,
            feelslike_f: 50.7,
            heatindex_c: 10.3,
            heatindex_f: 50.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651467600,
            time: "2022-05-02 07:00",
            temp_c: 10.9,
            temp_f: 51.6,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 89,
            feelslike_c: 11.1,
            feelslike_f: 52.0,
            heatindex_c: 10.9,
            heatindex_f: 51.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651471200,
            time: "2022-05-02 08:00",
            temp_c: 11.8,
            temp_f: 53.2,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 81,
            feelslike_c: 12.1,
            feelslike_f: 53.8,
            heatindex_c: 11.8,
            heatindex_f: 53.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651474800,
            time: "2022-05-02 09:00",
            temp_c: 13.7,
            temp_f: 56.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 46,
            feelslike_c: 14.2,
            feelslike_f: 57.6,
            heatindex_c: 13.7,
            heatindex_f: 56.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651478400,
            time: "2022-05-02 10:00",
            temp_c: 15.6,
            temp_f: 60.1,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 64,
            feelslike_c: 15.6,
            feelslike_f: 60.1,
            heatindex_c: 15.6,
            heatindex_f: 60.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651482000,
            time: "2022-05-02 11:00",
            temp_c: 17.1,
            temp_f: 62.8,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 62,
            feelslike_c: 17.1,
            feelslike_f: 62.8,
            heatindex_c: 17.1,
            heatindex_f: 62.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651485600,
            time: "2022-05-02 12:00",
            temp_c: 18.0,
            temp_f: 64.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 51,
            feelslike_c: 18.0,
            feelslike_f: 64.4,
            heatindex_c: 18.0,
            heatindex_f: 64.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651489200,
            time: "2022-05-02 13:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651492800,
            time: "2022-05-02 14:00",
            temp_c: 16.3,
            temp_f: 61.3,
            is_day: 1,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 16.3,
            feelslike_f: 61.3,
            heatindex_c: 16.3,
            heatindex_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651496400,
            time: "2022-05-02 15:00",
            temp_c: 16.0,
            temp_f: 60.8,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 63,
            feelslike_c: 16.0,
            feelslike_f: 60.8,
            heatindex_c: 16.0,
            heatindex_f: 60.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651500000,
            time: "2022-05-02 16:00",
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            cloud: 66,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            will_it_rain: 1,
            chance_of_rain: 78,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651503600,
            time: "2022-05-02 17:00",
            temp_c: 16.5,
            temp_f: 61.7,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 60,
            feelslike_c: 16.5,
            feelslike_f: 61.7,
            heatindex_c: 16.5,
            heatindex_f: 61.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651507200,
            time: "2022-05-02 18:00",
            temp_c: 15.8,
            temp_f: 60.4,
            is_day: 1,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            cloud: 41,
            feelslike_c: 15.8,
            feelslike_f: 60.4,
            heatindex_c: 15.8,
            heatindex_f: 60.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651510800,
            time: "2022-05-02 19:00",
            temp_c: 14.6,
            temp_f: 58.3,
            is_day: 1,
            condition: {
              text: "Patchy rain possible",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            cloud: 65,
            feelslike_c: 14.1,
            feelslike_f: 57.4,
            heatindex_c: 14.6,
            heatindex_f: 58.3,
            will_it_rain: 0,
            chance_of_rain: 68,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651514400,
            time: "2022-05-02 20:00",
            temp_c: 13.1,
            temp_f: 55.6,
            is_day: 1,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            cloud: 70,
            feelslike_c: 12.7,
            feelslike_f: 54.9,
            heatindex_c: 13.1,
            heatindex_f: 55.6,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651518000,
            time: "2022-05-02 21:00",
            temp_c: 12.5,
            temp_f: 54.5,
            is_day: 0,
            condition: {
              text: "Overcast",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            cloud: 100,
            feelslike_c: 12.0,
            feelslike_f: 53.6,
            heatindex_c: 12.5,
            heatindex_f: 54.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651521600,
            time: "2022-05-02 22:00",
            temp_c: 11.7,
            temp_f: 53.1,
            is_day: 0,
            condition: {
              text: "Cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            cloud: 74,
            feelslike_c: 10.8,
            feelslike_f: 51.4,
            heatindex_c: 11.7,
            heatindex_f: 53.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
          {
            time_epoch: 1651525200,
            time: "2022-05-02 23:00",
            temp_c: 11.2,
            temp_f: 52.2,
            is_day: 0,
            condition: {
              text: "Partly cloudy",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            cloud: 58,
            feelslike_c: 10.5,
            feelslike_f: 50.9,
            heatindex_c: 11.2,
            heatindex_f: 52.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
          },
        ],
      },
    ],
  },
};
